apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-index
  namespace: default
data:
  index.html: |
    <html>
      <head>
        <title>Web dari HTTPD</title>
      </head>
      <body>
        <h1>Hello dari cluster K3s!</h1>
        <p>Nama saya Daeng</p>
      </body>
    </html>
